language: julia

julia:
    - 1.3
    - 1.4
    - nightly

os:
    - linux
    - osx
    - windows

arch:
    - amd64
    - arm64


notifications:
  email: false
  
matrix:
    allow_failures:
        - julia: nightly

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.activate("."); Pkg.test()'
  - for script in example/*; do julia $script; done
  - for script in benchmark/*; do julia $script; done
