language: julia

julia:
    - 1.4
    - 1.5
    - nightly

os:
    - linux
    - osx
    - windows

arch:
    - amd64
    - arm64


notifications:
  email: false
  
matrix:
    allow_failures:
        - julia: nightly

script:
  - JULIA_DEBUG=AMCL julia --project --check-bounds=yes -e 'import Pkg; Pkg.activate("."); Pkg.test()'
  - for script in example/*; do echo "== $script =="; julia $script; done
